server:
  port: 8082


spring:
  #jackson:
  #  serialization:
  #    fail-on-empty-beans: false
  cache:
    type: simple
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Nupur@29
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          oauth2-client-credentials:
            client-id: employee-portal
            client-secret: WrquI8P0hrErMX0e3gNFnfFlXGf4icpW
            provider: keycloak
            scope: openid, profile, roles
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/techintroductory
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/techintroductory/protocol/openid-connect/certs